## Geog/Geosci523
### Lab 6:  Dissimilarity Analyses

### Things to Do Before Class

#### Install Packages
Ensure that `analogue` and `vegan` have been installed on your version of R.

#### Read:
Jackson, S. T., and Williams, J. W. (2004) Modern analogs in Quaternary paleoecology: Here today, gone yesterday, gone tomorrow? Annual Review of Earth and Planetary Sciences 32:495-537.

Radeloff, V. C., Williams, J. W., Bateman, B. L., Burke, K. D., Carter, S. K., Childress, E. S., Cromwell, K., Gratton, C., Hasley, A. O., Kraemer, B. M., Latzka, A. W., Marin-Spiotta, E., Meine, C. D., Munoz, S. E., Neeson, T. M., Pidgeon, A. M., Rissman, A. R., Rivera, R. J., Szymanski, L. M., and Usinowicz, J. (2015) The rise of novelty in ecosystems. Ecological Applications 25:2051-2068.

#### Other Good Readings:
Mottl, O., Grytnes, J.A., Seddon, A.W., Steinbauer, M.J., Bhatta, K.P., Felde, V.A., Flantua, S.G.A., Birks, H.J.B., 2021. Rate-of-change analysis in paleoecology revisited: A new approach. . Rev. Palaeobot. Palynology 29, 104483.

Mottl, O., Flantua, S.G.A., Bhatta, K.P., Felde, V.A., Giesecke, T., Goring, S., Grimm, E.C., Haberle, S., Hooghiemstra, H., Ivory, S., Kuneš, P., Wolters, S., Seddon, A.W.R., Williams, J.W., 2021. Global acceleration in rates of vegetation change over the last 18,000 years. Science 321, 860-864.

Telford, R. J., and Birks, H. J. B. (2005) The secret assumption of transfer functions:  problems with spatial autocorrelation in evaluating model performance. Quaternary Science Reviews 24:2173-2179.

Williams, J. W., and Shuman, B. (2008) Obtaining accurate and precise environmental reconstructions from the modern analog technique and North American surface pollen dataset. Quaternary Science Reviews 27:669-687.
