---
title: "Lab 10: Proxy system modelling"
author:
  name: "Quinn Asena and Jack Williams"
date: today
bibliography: refs.bib
format:
  html:
    code-fold: false
    link-external-newwindow: true
theme:
  light: flatly
  dark: darkly
---

# Before the Lab

In the lab we will be discussing two related (but distinct) concepts: Proxy System Modelling [@evans2013] and 'random' pattern generation [@blaauw2010a].

**Read:**

- @evans2013

- @blaauw2010a

**Discussion points to consider:**

- What do you think of the proxy system model approach?

- What is the main concept from @blaauw2010a?

- How do these two concepts relate to each other?

We will have a informal round-table discussion, so come with some notes, questions, and/or further discussion points.


# Goals

- Understand proxy system modelling, and challenges around differentiating pattern from proces.

- Build your own 'random' time series!  (And, sharpen your R/Rmarkdown skills along the way)


# Background

Historically, palaeoecology was at first a mostly descriptive and qualitative discipline, which was non-trivial: being able to reconstruct past environments from indirect proxies such as fossil pollen was a major scientific advancement! Since, laboratory and statistical methods have rapidly advanced with more accurate dating techniques, Bayesian age-depth modelling, and statistical analyses, allowing us to make more inferences about, for example, the timing and causes of ecological events. However, determining the synchroneity of events across time and space remains a major challenge to palaeo-science [@parnell2008].

Now, palaeoecology is also concerned with better understanding the underlying processes, and using the past to inform the future [@jackson2007]. Understanding change in ecosystems may require data with a temporal extent (relative to the pressures they may be experiencing) that extends beyond sources such as instrumental monitoring data or written records. As such, palaeoecological methods can be used to increase understanding of how ecosystems and environments respond to changing climates, disturbances and anthropogenic pressures beyond data collected about current or recent historic conditions [@kosnik2016].

![@kosnik2016: "The characteristics and temporal coverage for different data types in the context of human cultural development. Record types are scored as dominantly of that category (black), some of that category (grey), or typically not of that category (white). The y-axis is log-transformed even though this visually exaggerates the temporal extent of instrumental and experimental records..." see ref for details.](https://royalsocietypublishing.org/cms/asset/3fa60131-834f-4658-9faa-7af81742940a/rsbl20150951f01.jpg)

If palaeo-data are to be used to make inferences about the causes of contemporary ecosystem change, or predictions of future ecosystem states, it is crucial to quantify uncertainties about the data and test ecological theories. It is challenging to empirically test theories at the ecosystem level (e.g., the spacial extent captured by pollen in a lake sediment core), and over the time-scales required, often multiple generations of species. Thus various modelling approaches can be used to test hypotheses, theories, quantify uncertainty, and many other applications [@perry2016].

This general need has led to the development of proxy system models [@evans2013], which try to represent the processes that relate the response of a proxy (or sensor) to the environmental or ecological signal of interest.  T

Modelling approaches range from the very precise (e.g., including as many processes and measurements as possible) to the very general. Some models are more deterministic, while others rely more on stochastic processes. The utility of any model depends on the question 'Is it useful for its purpose?'. In this lab, we will implement a very general (and simple) model developed by @blaauw2010a designed to demonstrate a simple but important question for palaeoecologists: Can we differentiate 'random' patterns from causal processes?


# Homework

:::{.callout-note}
# Part 1: Explore the model
1. Find the supplimentary information from @blaauw2010a, download and unzip it. It is an R script file containing two functions

2. Open and run the entire script. The two functions are called `RandomEnv()` and `RandomProx()` (you will see them appear in your global environment after running the script)

    i) The functions have default arguments and automatically generate plots.

3. Run the functions in your console with the default arguments (`RandomEnv()`, `RandomProx()`) several times each to see how the output changes

    i) You will see the default parameters in the script, i.e., `nprox = 15`. Try meddle with them to generate different output. You don't need to edit the script, only run the function with a user-defined argument *e.g.,* `RandomEnv(nprox = 10)`.
:::

:::{.callout-note}
# Part 2: A little R Markdown
1. In RStudio go 'file -> New File -> R Markdown'

    i) Fill in the title with your name (leave other settings default)

This will open a template R Markdown file. You can run it right away with the 'knit' button to see what the output looks like.

2. Make sure the 'Random.R' file from @blaauw2010a is in the same directory as your markdown file.

3. You will see three code chunks in the template. In the first code chunk, replace the contents with `source("Random.R")`.

    i) Run the code chunk with the little green 'play' button to make sure there is no error.

4. Replace the contents of the following two code chunks with:

    i) In _both_ code chunks insert `set.seed()` choose a number to put inside the perentheses

    ii) insert the functions `RandomEnv()` and `RandomProx()` (one in each of the two code chunks below `set.seed()`)

5. Replace the two headings (the text follong the `##`) with your own headings and remove the template text

6. Create a final heading using `## heading name` and comment on how you would visually interpret both plots above.

(Usually we would include statistical analyses but visual inspection is sufficient for today's goals.)
:::

:::{.callout-note}
# Part 3: Reflection
1. Consider how you would interpret the time series that you've generated as if they were empirical records vs how you know they were generated.

2. Without writing actual code, describe how you might try to build upon statistical simulations like these to answer questions and test hypotheses, e.g. (1) distingiush random variations versus ecological events caused by a climatic driver; (2) test for interactions among species; and (3) assess whether an ecological event seen across multiple sites is due to chance or indicates a true event observed at multiple locations.  What additional variables or datasets would you incorporate?  Would you work with real-world or simulated (pseudo-proxy data)?  As usual in science, there is no single right answer and lots of ways of tackling an interesting question.

These last two questions can be in less than 500 words but we won't word count. @perry2016 is a very useful discussion of different uses of modelling, including null models and pattern-oriented modelling. You can include your answers in your R Markdown file.  Make sure your R Markdown script knits (it will generate an HTML file) and submit both your `.Rmd` and `.html` files to canvas.

:::


# References
